"""
PowerPoint generation from content for document tools.
"""
import asyncio
from pathlib import Path
from typing import Dict, List, Optional
import tempfile
import logging

from daip_live.doc.models.document_models import PPTGenerationResult


class PPTGenerator:
    """Generate PowerPoint presentations from content."""
    
    def __init__(self):
        self.name = "PowerPoint Generator"
        self.logger = logging.getLogger(__name__)
        self._init_presentation_template()
    
    def _init_presentation_template(self):
        """Initialize default presentation templates."""
        self.default_templates = {
            'academic': {
                'title_font': 'Arial',
                'content_font': 'Arial',
                'title_size': 32,
                'content_size': 18,
                'colors': {
                    'title': '#1E3A8A',  # Dark blue
                    'content': '#0F172A',  # Dark gray
                    'background': '#FFFFFF'  # White
                }
            },
            'business': {
                'title_font': 'Calibri',
                'content_font': 'Calibri',
                'title_size': 36,
                'content_size': 16,
                'colors': {
                    'title': '#2563EB',  # Blue
                    'content': '#374151',  # Gray
                    'background': '#F9FAFB'  # Light gray
                }
            },
            'technical': {
                'title_font': 'Consolas',
                'content_font': 'Consolas',
                'title_size': 28,
                'content_size': 14,
                'colors': {
                    'title': '#4338CA',  # Indigo
                    'content': '#4B5563',  # Gray
                    'background': '#1F2937'  # Dark gray
                }
            }
        }
    
    async def generate_from_content(self, 
                                   content: str, 
                                   title: str, 
                                   output_path: Path,
                                   template: str = 'academic') -> PPTGenerationResult:
        """Generate a PowerPoint from content."""
        start_time = asyncio.get_event_loop().time()
        
        result = PPTGenerationResult(
            source_content=content,
            presentation_title=title,
            slide_count=0,
            output_path=str(output_path),
            success=False
        )
        
        try:
            # Import python-pptx only when needed to avoid dependency issues
            from pptx import Presentation
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor
            from pptx.enum.text import PP_ALIGN
            from pptx.enum.shapes import MSO_SHAPE
            from pptx.enum.chart import XL_CHART_TYPE
            
            # Create presentation
            prs = Presentation()
            
            # Process content into slides
            slides_content = self._parse_content_to_slides(content)
            
            # Create title slide
            if title or slides_content:
                title_slide_layout = prs.slide_layouts[0]  # Title slide layout
                title_slide = prs.slides.add_slide(title_slide_layout)
                
                title_shape = title_slide.shapes.title
                if title_shape:
                    title_shape.text = title or "Generated Presentation"
                
                subtitle_shape = title_slide.placeholders[1] if len(title_slide.placeholders) > 1 else None
                if subtitle_shape:
                    subtitle_shape.text = "Generated by DAIP-LIVE Document Tools"
            
            # Create content slides
            slide_titles = []
            for i, (slide_title, slide_content) in enumerate(slides_content):
                content_slide_layout = prs.slide_layouts[1]  # Title and Content layout
                content_slide = prs.slides.add_slide(content_slide_layout)
                
                title_shape = content_slide.shapes.title
                if title_shape:
                    title_shape.text = slide_title
                    slide_titles.append(slide_title)
                
                content_shape = content_slide.placeholders[1] if len(content_slide.placeholders) > 1 else None
                if content_shape:
                    content_shape.text = slide_content[:2000]  # Limit content to avoid overflow
            
            # Save presentation
            prs.save(str(output_path))
            
            end_time = asyncio.get_event_loop().time()
            
            result.success = True
            result.slide_count = len(slides_content) + 1  # +1 for title slide
            result.slide_titles = slide_titles
            result.generation_time = end_time - start_time
            
        except ImportError:
            # python-pptx not installed - return error result
            end_time = asyncio.get_event_loop().time()
            result.error_message = "python-pptx library not installed. Install with: pip install python-pptx"
            result.generation_time = end_time - start_time
            self.logger.error("PowerPoint generation failed: python-pptx not available")
            
        except Exception as e:
            end_time = asyncio.get_event_loop().time()
            result.error_message = str(e)
            result.generation_time = end_time - start_time
            self.logger.error(f"PowerPoint generation error: {e}")
        
        return result
    
    def _parse_content_to_slides(self, content: str) -> List[tuple[str, str]]:
        """Parse content into slide titles and content."""
        lines = content.split('\n')
        slides = []
        current_title = "Introduction"
        current_content = []
        
        for line in lines:
            line = line.strip()
            
            if not line:
                continue
            
            # Level 1 headings become slide titles
            if line.startswith('# '):
                if current_title and current_content:
                    # Save previous slide
                    slides.append((current_title, '\n'.join(current_content)))
                
                current_title = line[2:] if len(line) > 2 else "Untitled Slide"
                current_content = []
            elif line.startswith('## '):
                # Level 2 headings could also become new slides or sections
                if len(current_content) > 10:  # If we have substantial content in current slide
                    # Save current content before starting new section
                    if current_title and current_content:
                        slides.append((current_title, '\n'.join(current_content)))
                    
                    current_title = line[3:] if len(line) > 3 else "Section"
                    current_content = []
                else:
                    current_content.append(f"**{line[3:]}**")  # Bold section heading in content
            elif line.startswith('### '):
                # Level 3 headings become sub-points
                current_content.append(f"**{line[4:]}**")
            elif line.startswith(('- ', '* ', '+ ')):
                # List items
                current_content.append(f"• {line[2:]}")
            elif line.startswith(('1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.')):
                # Numbered items
                current_content.append(line)
            else:
                # Regular content
                current_content.append(line)
        
        # Add final slide if content exists
        if current_title and current_content:
            slides.append((current_title, '\n'.join(current_content)))
        elif not slides:
            # If no slides were created, create at least one with the full content
            slides.append(("Generated Presentation", content[:2000]))  # Limit to avoid overflow
        
        return slides
    
    async def generate_from_structure(self, 
                                    structure: Dict[str, List[str]], 
                                    title: str,
                                    output_path: Path,
                                    template: str = 'academic') -> PPTGenerationResult:
        """Generate PowerPoint from structured data."""
        content = self._structure_to_content(structure)
        return await self.generate_from_content(content, title, output_path, template)
    
    def _structure_to_content(self, structure: Dict[str, List[str]]) -> str:
        """Convert structured data to content for slide generation."""
        content_parts = []
        
        for key, value in structure.items():
            if isinstance(value, list):
                content_parts.append(f"# {key}")
                for item in value:
                    content_parts.append(f"- {item}")
                content_parts.append("")
            elif isinstance(value, str):
                content_parts.append(f"# {key}")
                content_parts.append(value)
                content_parts.append("")
            elif isinstance(value, dict):
                content_parts.append(f"# {key}")
                for subkey, subval in value.items():
                    content_parts.append(f"## {subkey}")
                    content_parts.append(str(subval))
                content_parts.append("")
        
        return '\n'.join(content_parts)